// pack-assets.ts: the STANDARD BASELINE PACK, and nothing else any more.
//
// A picture for every one of internal/mapdef/standard.go's ELEVEN standard
// natures, so a square with no art override draws SOMETHING rather than nothing
// — before this existed, zero code anywhere produced a std:<kind>/<material>
// image and both shipped adventures carry no overrides at all (review finding
// C2, 2026-08-16: goblin-ambush's earth floor, cellar-rats' wood floor, every
// square blank).
//
// IT IS A PACK AND IT KEEPS THE NAME. client/public/std-pack/pack.json is a
// real pack manifest on disk, generated by tools/genmappack, and this file
// reads it. What LEFT is the per-pack half: packFileURL, packManifestURL,
// imageRequestsForPack and loadPackImages all talked to
// GET /api/packs/{pack}/{file}, which 2026-09-02-art-is-a-flat-library Task 7
// deleted along with mapdef.Pack itself. Task 6 of that plan removed them here,
// and view/art-assets.ts is what replaces them: one flat art/ directory, one
// route, no manifest, no container.
//
// THEY WERE ALREADY DEAD BEFORE THEY WERE DELETED, which is the reason
// client/test/art-assets.test.ts now carries an absence test for them. Task 5
// dropped the pack reference from GET /api/maps, so app.ts's loadMapPacks
// iterated and found nothing on every boot — while the TypeScript still
// compiled, still typechecked, and said nothing at all. Nothing shouts about
// inert code.
//
// THE STANDARD PACK IS SERVED FROM A DIFFERENT PLACE, deliberately, and that is
// why none of this moved to art-assets.ts. GET /api/art/{file} exists for
// OPERATOR-INSTALLED content — third-party trust, Bearer-authenticated, served
// through a closed content-type allowlist (internal/gateway/metadata.go's own
// doc section). The standard pack is FIRST-PARTY: generated by this repository's
// own tool, at this repository's own commit, shipped in the SAME build artifact
// as index.html/index.js. It is served from "/std-pack/..." — a plain sibling of
// the client bundle's own static files (client/public/std-pack, copied verbatim
// by Vite into cmd/vtt/webdist/std-pack) — through the gateway's existing
// unauthenticated static route (internal/gateway/server.go's WithStatic: "the
// browser must load the app before it has anywhere to type a token"). No pack
// id, no token: every function below takes neither.

import type { ImageMap } from "./canvas";

/**
 * PackManifestJSON is pack.json's raw on-disk shape, fetched and parsed AS
 * AUTHORED — the static route serves the file's own bytes verbatim
 * (internal/gateway/server.go's WithStatic), never re-marshalled — so the field
 * names here are the snake_case ones tools/genmappack actually writes.
 *
 * IT NO LONGER MIRRORS ANY GO TYPE. This shape matched internal/mapdef's
 * packJSON/packTileJSON until 2026-09-02-art-is-a-flat-library Task 7 deleted
 * mapdef.Pack and its loader; what it describes now is one committed file,
 * client/public/std-pack/pack.json, written by tools/genmappack/std_pack.go and
 * read by nothing else.
 */
export interface PackManifestJSON {
  id: string;
  name: string;
  cell_px: number;
  tiles: PackManifestTileJSON[];
  objects: PackManifestTileJSON[];
}

/** One tiles[] or objects[] entry — the two arrays share this shape
 *  (mapdef.PackTile's own doc comment: "a pack.json entry looks identical
 *  whichever list it sits in"). Every field but `name` is optional: kind and
 *  material are advisory-only (spec §3.2) and a tile has EITHER `file` OR
 *  the `file_open`/`file_closed` pair, never a use for all three. */
export interface PackManifestTileJSON {
  name: string;
  kind?: string;
  material?: string;
  file?: string;
  file_open?: string;
  file_closed?: string;
  desc?: string;
}

/** One file to fetch, and the ImageMap key canvas.ts's paint() should find
 *  it under once decoded. */
export interface ImageRequest {
  key: string;
  url: string;
}

/**
 * standardPackFileURL is where the baseline pack's files live: a plain sibling
 * of the client bundle's own static files, unauthenticated, no pack id. See
 * this file's header for why that is a different place from
 * GET /api/art/{file} rather than an inconsistency.
 */
export function standardPackFileURL(base: string, file: string): string {
  return `${base}/std-pack/${encodeURIComponent(file)}`;
}

/**
 * imageRequestsForStandardPack decides WHAT to fetch and WHERE each answer
 * belongs in the ImageMap — pure, so it is fully unit-tested with no network and
 * no image decoder.
 *
 * THE KEY COMES FROM EACH TILE'S kind/material, NEVER ITS NAME, and that is the
 * one thing about this pack that differs from any other: scene-plan.ts's
 * tileImage resolves an
 * unoverridden square to `std:${tile.Kind}/${tile.Material}` — it has no
 * notion of this pack's own tile NAMES (those are genmappack's own
 * bookkeeping, kept in pack.json only for a human reading the file) — so
 * keying by name here would produce keys tileImage can never ask for.
 *
 * A tile naming no kind or material is skipped rather than guessed at: a
 * genuine std pack.json (tools/genmappack/std_pack.go) always sets both, so
 * this is defensive against a malformed file, not an expected path.
 */
export function imageRequestsForStandardPack(
  base: string,
  manifest: PackManifestJSON,
): ImageRequest[] {
  const out: ImageRequest[] = [];
  for (const t of manifest.tiles) {
    if (!t.kind || !t.material) continue;
    const key = `std:${t.kind}/${t.material}`;
    if (t.file) out.push({ key, url: standardPackFileURL(base, t.file) });
    if (t.file_closed) out.push({ key, url: standardPackFileURL(base, t.file_closed) });
    if (t.file_open) out.push({ key: `${key}/open`, url: standardPackFileURL(base, t.file_open) });
  }
  return out;
}

/**
 * loadStandardPackImages fetches the baseline manifest and every image it names,
 * and resolves an ImageMap ready to hand straight to paint().
 *
 * A single file that 404s, or a decode that throws, drops JUST that key rather
 * than the whole pack, and the returned promise never rejects on either — the
 * same posture art-assets.ts's loadArtImages takes for a campaign's own art, and
 * for the same reason: a board that draws one square plain beats a board that
 * does not draw.
 *
 * No token anywhere, unlike loadArtImages: this pack ships inside the client
 * bundle and carries nothing that needs gating.
 *
 * decode defaults to the browser's own createImageBitmap. Neither bun's test
 * runtime nor happy-dom implements it (canvas.ts's own header comment), so every
 * test injects a stand-in; app.ts, the one production call site, never overrides
 * it.
 */
export async function loadStandardPackImages(
  base: string,
  fetchImpl: typeof fetch = fetch,
  decode: (blob: Blob) => Promise<CanvasImageSource> = createImageBitmap,
): Promise<ImageMap> {
  const manifestResp = await fetchImpl(standardPackFileURL(base, "pack.json"));
  if (!manifestResp.ok) return {};
  const manifest = (await manifestResp.json()) as PackManifestJSON;

  const images: ImageMap = {};
  await Promise.all(
    imageRequestsForStandardPack(base, manifest).map(async (req) => {
      try {
        const resp = await fetchImpl(req.url);
        if (!resp.ok) return;
        images[req.key] = await decode(await resp.blob());
      } catch {
        // See this function's own doc comment: one bad file must not take
        // down the rest, or reject the whole load.
      }
    }),
  );
  return images;
}
