// std_pack.go: the STANDARD vocabulary's own baseline pack (review finding
// C2, 2026-08-16) — a picture for every one of the eleven natures
// internal/mapdef/standard.go declares, so a square with NO art override
// still draws something. Before this file, the only pack genmappack
// produced was maps/cellar's own starter pack, which happens to override
// 100% of its squares — the reason C2 went unnoticed for as long as it did.
//
// A SEPARATE pack from maps/cellar's, deliberately: the starter pack is
// authored CONTENT (an example of what a pack author writes, per main.go's
// own header comment), while this one is PLATFORM vocabulary — the same
// eleven names mapdef.StandardTile resolves, with exactly one picture (two
// for the door) apiece. Mixing the two would make maps/cellar's pack.json
// stop being the honest "here is what an author writes" example it is meant
// to be.
//
// WHERE THIS SHIPS (Patrik's ruling): the client's own bundle, not the
// authenticated GET /api/packs/{pack}/{file} route. That route exists for
// OPERATOR-INSTALLED content (--maps-dir, spec §4.2's trust framing: "same
// trust as guide.md, but more likely third-party") and its whole security
// posture — packFileContentTypes' closed allowlist, os.OpenRoot's
// symlink-safety, the Bearer-auth gate — is built for exactly that: content
// this binary did not itself produce. The standard pack is the opposite: it
// is generated by THIS repository's own tool, at THIS repository's own
// commit, and ships in the SAME artifact as index.html and index.js.
// Routing it through the untrusted-pack pipe would blur a trust boundary
// that exists on purpose; serving it from the client's own static bundle
// keeps first-party platform art on the same footing as the program itself
// (server.go's own WithStatic doc comment: "the browser must load the app
// before it has anywhere to type a token... What is public here is the
// PROGRAM"). It also means std art is available even when the server has no
// --maps-dir/--adventures-dir configured at all, and even before a token
// exists — unlike a WithMaps/WithPackFiles pack, which loadMapsDir only
// ever wires in when mapsDir != "" (cmd/vtt/serve_compose.go).
//
// client/public/std-pack (this file's own -std-out default) is Vite's
// convention for "copy verbatim into the build output" (client/vite.config.ts
// sets no publicDir override, so Vite's own default — "public" under root —
// applies): `task build:client` lands these files at
// cmd/vtt/webdist/std-pack/*, served unauthenticated by the SAME
// http.FileServerFS mux entry that already serves index.html/index.js.
// client/src/view/pack-assets.ts's loadStandardPackImages fetches from
// there directly (no token, no /api prefix) — see that file's own comment
// for the client-side half of this decision.
package main

import (
	"image"
	"math/rand"
)

// standardEntry is one of internal/mapdef/standard.go's eleven natures, plus
// the drawing this tool must produce for it. name/kind/material are checked
// against mapdef.StandardTile/StandardTileNames in std_pack_test.go — this
// table is the ONLY place that check can fail, by construction, because the
// test walks this slice rather than a second hand-typed list of eleven
// names.
type standardEntry struct {
	name, kind, material string
	desc                 string

	// A non-door entry sets file+draw; a door sets fileOpen+fileClosed and
	// drawOpen+drawClosed instead — never both shapes, checked by
	// TestStandardPackEveryEntryHasArt.
	file                 string
	draw                 func(*image.RGBA, *rand.Rand)
	fileOpen, fileClosed string
	drawOpen, drawClosed func(*image.RGBA, *rand.Rand)
}

// standardEntries: every one of mapdef.standardTiles' eleven names,
// kind/material copied from internal/mapdef/standard.go by hand ONCE here —
// the test above is what keeps this copy from silently drifting, not
// avoiding the copy itself (mapdef's own map is unexported, so this file
// cannot read it directly without importing mapdef's internals, which would
// wire a content-generation tool to engine internals for no reason a change
// to either side should have to consider).
//
// Reuses four of maps/cellar's own drawing functions where the NATURE is
// literally the same texture family (wall/stone, floor/stone, floor/earth,
// door/wood) — a stone wall is a stone wall whether it is the standard
// baseline or cellar-basics' own masonry-1. The remaining seven natures have
// no cellar-pack equivalent and get their own drawStd* function below.
var standardEntries = []standardEntry{
	{
		name: "stone-wall", kind: "wall", material: "stone",
		desc: "coursed stone blockwork, the standard wall face for any nature naming no art of its own",
		file: "std_stone_wall.png", draw: drawMasonry,
	},
	{
		name: "wood-wall", kind: "wall", material: "wood",
		desc: "upright wooden wall planking",
		file: "std_wood_wall.png", draw: drawStdWoodWall,
	},
	{
		name: "wood-door", kind: "door", material: "wood",
		desc: "a banded wooden door; closed and open are the SAME nature (spec §3.3) — folded state " +
			"picks which of these two pictures the renderer draws, never the tile's kind",
		fileClosed: "std_wood_door_closed.png", fileOpen: "std_wood_door_open.png",
		drawClosed: drawDoorClosed, drawOpen: drawDoorOpen,
	},
	{
		name: "stone", kind: "floor", material: "stone",
		desc: "cut flagstone paving",
		file: "std_stone_floor.png", draw: drawFlagstone,
	},
	{
		name: "wood", kind: "floor", material: "wood",
		desc: "wooden floorboards",
		file: "std_wood_floor.png", draw: drawStdWoodFloor,
	},
	{
		name: "earth", kind: "floor", material: "earth",
		desc: "packed dirt floor, uneven and speckled with small stones",
		file: "std_earth_floor.png", draw: drawEarth,
	},
	{
		name: "grass", kind: "floor", material: "grass",
		desc: "short grass, blade-flecked",
		file: "std_grass_floor.png", draw: drawStdGrass,
	},
	{
		name: "sand", kind: "floor", material: "sand",
		desc: "loose pale sand",
		file: "std_sand_floor.png", draw: drawStdSand,
	},
	{
		name: "water", kind: "floor", material: "water",
		desc: "shallow, rippled water",
		file: "std_water_floor.png", draw: drawStdWater,
	},
	{
		name: "metal", kind: "floor", material: "metal",
		desc: "riveted metal plating",
		file: "std_metal_floor.png", draw: drawStdMetal,
	},
	{
		name: "ice", kind: "floor", material: "ice",
		desc: "frozen ice, cracked",
		file: "std_ice_floor.png", draw: drawStdIce,
	},
}

// writeStandardPack draws and writes every entry in standardEntries into
// out, and returns the packOut manifest it also persists as out/pack.json —
// returned (not just written) so std_pack_test.go can assert on it directly
// without re-parsing its own output back off disk for every check.
//
// rng is threaded through from the caller's single seeded source (main's
// own doc comment on writeTile explains why: reproducibility covers the
// WHOLE run, not one pack in isolation).
//
// Objects is explicitly a non-nil empty slice, not the zero value: packOut's
// json tag carries no `omitempty` (main.go's own packOut/packTileOut are
// shaped for a human-readable file, not a decoder — see main.go's header
// comment), so a nil slice here would marshal as `"objects": null`, and
// pack-assets.ts's loadStandardPackImages iterates manifest.objects/tiles
// with a plain `for...of` that throws on null rather than an empty array.
// The standard vocabulary has no objects to declare (mapdef.StandardTile
// resolves kind/material for TILES only; scene-plan.ts's objectImage doc
// comment: "unlike a tile, an object has no standard vocabulary to fall
// back to") — an explicit empty slice says that honestly.
func writeStandardPack(out string, rng *rand.Rand) packOut {
	mustMkdirAll(out)

	tiles := make([]packTileOut, 0, len(standardEntries))
	for _, e := range standardEntries {
		if e.kind == "door" {
			tiles = append(tiles, writeDoor(out, rng, e.name, e.material, e.fileClosed, e.fileOpen, e.desc, e.drawClosed, e.drawOpen))
		} else {
			tiles = append(tiles, writeTile(out, rng, e.name, e.kind, e.material, e.file, e.desc, e.draw))
		}
	}

	manifest := packOut{
		ID:      "std",
		Name:    "Standard Vocabulary",
		CellPx:  size,
		Tiles:   tiles,
		Objects: []packTileOut{},
	}
	writeManifest(out, manifest)
	return manifest
}

// --- new standard-only textures -----------------------------------------
//
// Same "deliberately crude" ethos as main.go's own drawing primitives —
// flat fields, per-pixel brightness noise, a handful of lines/dots/rects.
// Each one exists to be UNAMBIGUOUS at a glance and clearly DIFFERENT from
// its seven siblings, not to be good art (main.go's own header comment).

// drawStdWoodWall: upright wall planking — VERTICAL seams, so it reads as a
// surface you cannot walk through, contrasted deliberately with
// drawStdWoodFloor's horizontal boards (same material, different nature).
func drawStdWoodWall(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0x6e, 0x4f, 0x33))
	noise(img, rng, 12)
	seam := colorRGBA(0x3f, 0x2c, 0x1a)
	for x := 0; x < size; x += 11 {
		vline(img, x, seam)
	}
}

// drawStdWoodFloor: floorboards — HORIZONTAL seams, the walkable counterpart
// to drawStdWoodWall.
func drawStdWoodFloor(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0x8a, 0x64, 0x3c))
	noise(img, rng, 12)
	seam := colorRGBA(0x55, 0x3a, 0x20)
	for y := 0; y < size; y += 13 {
		hline(img, y, seam)
	}
}

// drawStdGrass: green fill, heavy noise, a scatter of short darker blades —
// distinguishes it from drawEarth's round pebbles (grass is linear, dirt is
// not).
func drawStdGrass(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0x4c, 0x7a, 0x33))
	noise(img, rng, 14)
	blade := colorRGBA(0x2f, 0x54, 0x1e)
	for i := 0; i < 30; i++ {
		x, y := rng.Intn(size), rng.Intn(size-3)
		fillRect(img, x, y, x+1, y+3, blade)
	}
}

// drawStdSand: pale fill, single-pixel darker grains (finer than
// drawEarth's multi-pixel pebbles — sand and dirt should not read as the
// same texture at a glance).
func drawStdSand(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0xd9, 0xc0, 0x8a))
	noise(img, rng, 10)
	grain := colorRGBA(0xb8, 0x9e, 0x68)
	for i := 0; i < 40; i++ {
		x, y := rng.Intn(size), rng.Intn(size)
		img.SetRGBA(x, y, grain)
	}
}

// drawStdWater: blue fill with a few lighter horizontal ripple bands, jittered
// vertically so they do not read as a regular grid.
func drawStdWater(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0x2f, 0x66, 0x86))
	noise(img, rng, 8)
	ripple := colorRGBA(0x5b, 0x93, 0xae)
	for y := 8; y < size; y += 14 {
		hline(img, y+rng.Intn(4), ripple)
	}
}

// drawStdMetal: grey-blue fill, low noise (metal is smoother than stone),
// and a regular grid of small dark rivets.
func drawStdMetal(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0x7d, 0x82, 0x88))
	noise(img, rng, 6)
	rivet := colorRGBA(0x33, 0x35, 0x38)
	for gy := 10; gy < size; gy += 20 {
		for gx := 10; gx < size; gx += 20 {
			fillCircle(img, gx, gy, 2, rivet)
		}
	}
}

// drawStdIce: pale cyan fill, low noise, and a single jagged crack line built
// from short random-walk segments — deliberately NOT axis-aligned, so ice
// reads as fractured rather than tiled like drawFlagstone's mortar.
func drawStdIce(img *image.RGBA, rng *rand.Rand) {
	fill(img, colorRGBA(0xc9, 0xe8, 0xef))
	noise(img, rng, 6)
	crack := colorRGBA(0x93, 0xc4, 0xd1)
	x, y := 10, 6
	for i := 0; i < 8; i++ {
		nx := x + rng.Intn(7) - 3
		ny := y + size/8
		x0, x1 := x, nx
		if x1 < x0 {
			x0, x1 = x1, x0
		}
		fillRect(img, x0, y, x1+1, ny, crack)
		x, y = nx, ny
	}
}
