#!/usr/bin/env python3
"""Boundary tests for check-no-pack.py.

The gate's whole value is the line it draws between the removed CONTAINER and
three things that look exactly like it in a grep and must survive:

  1. Go's own `package` keyword and the English word — 820 `package` and 103
     `packages` among the 1857 occurrences in the files this gate reads,
     measured 2026-09-06 over the tree as the gate found it. A needle that
     matched them would red on line 1 of every .go file, which is a gate
     switched off before lunch.
  2. THE STANDARD BASELINE PACK, which keeps its name on purpose
     (client/src/view/pack-assets.ts's header says so in as many words): a
     first-party manifest generated by tools/genmappack, shipped in the client
     bundle, served unauthenticated from /std-pack/. It is not a container a map
     claims and it did not leave.
  3. The tests whose JOB is to prove the container is gone, which have to write
     the word down in order to assert its absence. NO PRODUCTION FILE is in this
     family: internal/mapdef/load.go was, for mapJSON.Pack, until the migration
     route was deleted on 2026-09-06 and strict decoding turned out to be the
     whole of the refusal.

So the second and third families are EXEMPT, by word, with reasons; the first is
a STRUCTURAL carve-out, because a 923-entry exemption table is not a table, it
is a switch in the off position. TheEnglishWordIsNotTheNeedle below is that
carve-out's boundary, and TheStandardBaselineIsNotTheContainer is the other
one. Both are the tests most likely to be destroyed by a later widening.

Run: python3 tools/check_no_pack_test.py
"""

import importlib.util
import io
import os
import pathlib
import shutil
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)

_spec = importlib.util.spec_from_file_location(
    "check_no_pack", os.path.join(_HERE, "check-no-pack.py"))
gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gate)


def tree(**files):
    """A temp source tree; returns its path. Keys use __ for subdirectories."""
    d = tempfile.mkdtemp()
    for name, body in files.items():
        p = pathlib.Path(d) / name.replace("__", "/")
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8")
    return d


def run(root):
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = gate.main(["check-no-pack.py", root])
    return code, out.getvalue(), err.getvalue()


class CodePositionsAreCaught(unittest.TestCase):
    """The defect: the container comes back one helper at a time."""

    def test_the_go_loader_is_caught(self):
        root = tree(**{"internal/mapdef/load.go": '''package mapdef

func LoadPack(dir string) (*Pack, error) { return nil, nil }
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("load.go:3", err)
            self.assertIn("LoadPack", err)
        finally:
            shutil.rmtree(root)

    def test_the_map_field_is_caught(self):
        """A struct tag is a Go raw string, so the FIELD NAME is the hit."""
        root = tree(**{"internal/mapdef/format.go": '''package mapdef

type Map struct {
	Pack string `json:"pack"`
}
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertEqual([w for _, _, w in gate.findings(root, {})[0]], ["Pack"])
        finally:
            shutil.rmtree(root)

    def test_the_gateway_route_handler_is_caught(self):
        root = tree(**{"internal/gateway/artfile.go": '''package gateway

func (s *Server) handlePackFile(w http.ResponseWriter, r *http.Request) {}
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("handlePackFile", err)
        finally:
            shutil.rmtree(root)

    def test_the_server_field_and_its_option_are_caught(self):
        root = tree(**{"internal/gateway/server.go": '''package gateway

type Server struct {
	packFS fs.FS
}

func WithPackFiles(root string) Option { return nil }
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packFS", err)
            self.assertIn("WithPackFiles", err)
        finally:
            shutil.rmtree(root)

    def test_a_typescript_helper_is_caught(self):
        root = tree(**{"client/src/view/assets.ts": '''export function packFileURL(base: string, id: string, file: string) {
  return `${base}/api/packs/${id}/${file}`;
}
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packFileURL", err)
        finally:
            shutil.rmtree(root)

    def test_a_python_helper_is_caught(self):
        root = tree(**{"tools/thing.py": '''def load_pack(d):
    return d
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("load_pack", err)
        finally:
            shutil.rmtree(root)

    def test_a_proto_message_and_its_field_are_both_caught(self):
        root = tree(**{"contract/vtt/v1/maps.proto": '''syntax = "proto3";
message PackRef { string pack_id = 1; }
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("PackRef", err)
            self.assertIn("pack_id", err)
        finally:
            shutil.rmtree(root)

    def test_a_rename_of_the_container_is_still_caught(self):
        """The reason the needle is a WORD SHAPE and not a list of names.

        The gate that internal/mapdef carries in Go
        (TestNoPackTypeOrLoaderRemainsInThisPackage) bans six exact strings —
        LoadPack, PackTile, PackFormatVersion, packJSON, packTileJSON,
        packTileMap. None of the four names below is on that list, and every
        one of them is the container growing back.
        """
        for spelling in ["loadEmbeddedPack", "packRegistry", "artPackIndex",
                         "PACK_DIR"]:
            root = tree(**{"internal/a/a.go": "package a\n\nvar %s = 1\n" % spelling})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 1, spelling)
                self.assertIn(spelling, err)
            finally:
                shutil.rmtree(root)

    def test_every_casing_and_separator_is_one_identifier(self):
        for spelling in ["pack", "Pack", "PACK", "packs", "pack_dir",
                         "packDir", "PackDir", "PACK_DIR", "packsDir"]:
            root = tree(**{"internal/a/a.go": "package a\n\nvar %s = 1\n" % spelling})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 1, spelling)
                self.assertIn(spelling, err)
            finally:
                shutil.rmtree(root)

    def test_an_identifier_interpolated_into_a_template_literal_is_caught(self):
        """`${...}` is CODE inside a string, and a gate that swallows it is blind there."""
        root = tree(**{"client/src/view/dm.ts":
                       "const s = `row ${packLabel(e)} end`;\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packLabel", err)
        finally:
            shutil.rmtree(root)

    def test_division_is_not_mistaken_for_a_regex_literal(self):
        """A wrong guess would blank the rest of the line and hide the hit."""
        root = tree(**{"client/src/a.ts":
                       "const half = total / 2;\nconst n = packCount / 2;\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packCount", err)
        finally:
            shutil.rmtree(root)

    def test_a_regex_literal_body_is_a_pattern_and_not_a_hit(self):
        """The shape an absence assertion in the client would have."""
        body = ("expect(Object.keys(routes).filter((k) => "
                "/pack/i.test(k))).toEqual([]);\n")
        root = tree(**{"client/test/surface.test.ts": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)


class TheEnglishWordIsNotTheNeedle(unittest.TestCase):
    """`package` is Go's keyword, and the boundary this gate lives or dies on.

    820 `package` and 103 `packages` in the files this gate reads, on
    2026-09-06. Every single .go file opens with one. A needle that matched them could only be
    greened by exempting every Go file in the repository, which is not a gate.

    The carve-out is STRUCTURAL and case-aware, not a word list: `pack`
    followed by `age` in the SAME case run. `packAgent` and `PackAge` are
    camel-case boundaries and stay hits — the lookahead is why.
    """

    def test_the_go_package_clause_is_not_a_hit(self):
        root = tree(**{"internal/mapdef/load.go": "package mapdef\n\nvar x = 1\n"})
        try:
            code, out, err = run(root)
            self.assertEqual(code, 0, err)
            self.assertIn("clean", out)
        finally:
            shutil.rmtree(root)

    def test_every_spelling_of_the_english_word_is_not_a_hit(self):
        """AND THIS ASSERTION HAS A CONSEQUENCE, stated so nobody reads it as
        coverage it is not.

        The carve-out is a SUBSTRING rule, so the very thing that clears
        `packagePath` and `Subpackage` below clears `ArtPackage`,
        `LoadPackage`, `handlePackageFile`, `PackageTile`, `packageFS`,
        `ErrPackageNotLoaded` and a `"package"` JSON key — the most idiomatic
        rename anyone reaching for a distribution unit would write. A green run
        here is NOT evidence that a renamed container would be caught; it is
        evidence that Go compiles. The gate's KNOWN LIMITS says so at length,
        the measurement that makes a tighter needle unavailable is there (304
        code positions across 37 `package`-family words), and the two halves
        that can be closed are closed in internal/mapdef — decodeStrict's
        DisallowUnknownFields for the file format, which refuses `"package"`
        without knowing the name (TestAMapDeclaringAPackOrAPackageIsStillRefused
        drives it), and TestNoPackTypeOrLoaderRemainsInThisPackage's banned list
        for that package's declarations.
        """
        for spelling in ["package", "packages", "PACKAGES", "PACKAGE_CLAUSE_RE",
                         "packageManager", "go_package", "package_fingerprint",
                         "unresolvable_packages", "Subpackage", "packagePath",
                         "declared_package", "run_package", "packaged",
                         "packager"]:
            root = tree(**{"internal/a/a.go": "package a\n\nvar %s = 1\n" % spelling})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 0, "%s: %s" % (spelling, err))
            finally:
                shutil.rmtree(root)

    def test_a_camel_boundary_after_the_stem_is_still_a_hit(self):
        """The hole a case-blind carve-out would open, and it is not theoretical.

        Lower-case the word first and `packAgent` becomes `packagent`, whose
        first four characters are followed by `age` — so a container helper
        called `packAgent`, `packAge` or `packAgency` would be filed under the
        English word and never reported. The needle keeps the case.
        """
        for spelling in ["packAgent", "PackAge", "packAgency"]:
            root = tree(**{"internal/a/a.go": "package a\n\nvar %s = 1\n" % spelling})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 1, spelling)
                self.assertIn(spelling, err)
            finally:
                shutil.rmtree(root)

    def test_the_carve_out_is_case_aware_at_the_needle_itself(self):
        """The SECOND guard on the case-aware rule, and it is not decoration.

        test_a_camel_boundary_after_the_stem_is_still_a_hit drives the whole
        gate over a temp tree; against the SHIPPED exemption table it is the
        only test that fails when the carve-out is made case-blind, and one
        test standing between the tree and a silent hole is a coverage claim
        this repo does not accept. This one asserts the same rule one layer
        down, on the compiled pattern, so a regression has to defeat two
        mechanisms rather than one.
        """
        for word in ["package", "Package", "PACKAGE", "packages", "PACKAGES",
                     "Subpackage", "packagePath", "packaged", "packager"]:
            self.assertIsNone(gate.NEEDLE.search(word),
                              "%s is the English word and must not match" % word)
        for word in ["packAgent", "PackAge", "packAgency", "pack", "Pack",
                     "PACK", "packs", "LoadPack", "PACK_DIR"]:
            self.assertIsNotNone(gate.NEEDLE.search(word),
                                 "%s names the container and must match" % word)

    def test_a_camel_boundary_after_the_stem_is_caught_in_a_json_key_too(self):
        """The same rule through a different masker.

        The .json path keeps KEY text and blanks everything else, so a
        case-blind carve-out would hide a renamed container in a map file as
        readily as in Go — and no other test drives that combination.
        """
        root = tree(**{"campaigns/example/maps/m.json":
                       '{\n  "packAgent": "cellar-basics"\n}\n'})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAgent", err)
        finally:
            shutil.rmtree(root)

    def test_the_english_word_spelled_with_the_stem_is_a_stated_hole(self):
        """WRITTEN DOWN RATHER THAN HIDDEN, and asserted so it cannot drift.

        Every one of these is the container wearing the English word, and every
        one is CLEAN here. That is the gate's largest limit; it is in KNOWN
        LIMITS with the measurement that makes a tighter needle unavailable.
        This test exists so the limit is a fact in the suite rather than a
        sentence in a docstring — if a future needle ever does catch these,
        this test fails and the limit gets deleted rather than left stale.

        The two halves that ARE closed live in internal/mapdef and are proved
        there, not here: the `"package"` key is refused by loadAs, and
        `Package{`, `ArtPackage`, `LoadPackage` and `PackageTile` are banned in
        that package's own declarations.
        """
        body = ("package mapdef\n\n"
                "type ArtPackage struct{}\n"
                "func LoadPackage(d string) (*ArtPackage, error) { return nil, nil }\n"
                "func handlePackageFile() {}\n")
        root = tree(**{"internal/mapdef/load.go": body,
                       "campaigns/example/maps/m.json":
                       '{"package": "cellar-basics"}\n'})
        try:
            code, out, err = run(root)
            self.assertEqual(code, 0, err)
            self.assertIn("clean", out)
        finally:
            shutil.rmtree(root)

    def test_a_json_key_spelled_with_escapes_is_a_stated_hole(self):
        """`"\\u0070ack"` is the key `pack` to every JSON parser, and WORD
        matches identifier runs over the raw characters, so it contributes
        `u0070ack` and is not reported. In KNOWN LIMITS; pinned here so the
        limit is a fact rather than a claim."""
        root = tree(**{"campaigns/example/maps/m.json":
                       '{"\\u0070ack": "cellar-basics"}\n',
                       "internal/a/a.go": "package a\n"})
        try:
            code, out, err = run(root)
            self.assertEqual(code, 0, err)
            self.assertIn("clean", out)
        finally:
            shutil.rmtree(root)

    def test_the_neighbouring_english_words_are_reported_on_purpose(self):
        """STATED, not discovered. `packet`, `packed` and `unpack` are NOT
        carved out: each is one keystroke from the container's own vocabulary
        (`unpackArt` is precisely how a loader comes back), and none occurs at
        a code position in this tree today — measured 2026-09-06. If one
        arrives, it goes in EXEMPT with a reason, which is a decision somebody
        makes in public rather than a silence.
        """
        for spelling in ["packet", "packed", "unpack", "packetSize"]:
            root = tree(**{"internal/a/a.go": "package a\n\nvar %s = 1\n" % spelling})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 1, spelling)
            finally:
                shutil.rmtree(root)


class TheStandardBaselineIsNotTheContainer(unittest.TestCase):
    """The std pack stays, and it keeps its name.

    client/public/std-pack/pack.json is a real manifest generated by
    tools/genmappack and read by client/src/view/pack-assets.ts. It is
    first-party, shipped in the same build artifact as index.html, and served
    unauthenticated from /std-pack/ — not through GET /api/art/{file} and not
    through any route a map's claim resolves against. What left is the
    per-container half: packFileURL, imageRequestsForPack, loadPackImages and
    GET /api/packs/{pack}/{file}.

    Its identifiers are therefore EXEMPT BY WORD rather than by file, so the
    files that carry them are still scanned for every other spelling — see
    test_an_exemption_allows_only_the_words_it_names.
    """

    def test_the_baseline_helpers_are_exempt_in_the_shipped_table(self):
        for word in ["standardPackFileURL", "imageRequestsForStandardPack",
                     "loadStandardPackImages", "PackManifestJSON",
                     "PackManifestTileJSON"]:
            self.assertTrue(
                any(word in allowed
                    for allowed, _ in gate.EXEMPT.values()
                    if allowed is not None),
                "%s is not exempt; the standard baseline would red the gate" % word)

    def test_the_generators_manifest_shape_is_exempt(self):
        for word in ["packOut", "packTileOut", "packFormatVersion",
                     "writeStandardPack"]:
            self.assertTrue(
                any(word in allowed
                    for allowed, _ in gate.EXEMPT.values()
                    if allowed is not None),
                "%s is not exempt; tools/genmappack would red the gate" % word)

    def test_the_manifests_own_json_keys_are_not_hits(self):
        """pack.json's KEYS are id/name/cell_px/tiles/objects. The file is
        NAMED for the thing, and this gate reads contents, not names."""
        root = tree(**{"client/public/std-pack/pack.json": (
            '{\n'
            '  "id": "std",\n'
            '  "name": "Standard baseline",\n'
            '  "cell_px": 64,\n'
            '  "tiles": [{"name": "stone-floor", "kind": "floor",\n'
            '             "material": "stone", "file": "stone_floor.png"}]\n'
            '}\n'),
            "internal/a/a.go": "package a\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)


class TheShippedTableDescribesThisTree(unittest.TestCase):
    """An exemption that no longer applies must rot LOUDLY.

    Every entry names a real file and a word that really occurs there at a code
    position. Rename `packish` or delete a refusal test and the entry stops
    describing anything — and a dead exemption is a hole that widens silently as
    the file around it changes. This is the same move
    check_mutation_test.py's test_every_gated_package_in_the_real_tree_is_
    resolvable makes: assert the table against the tree it governs.
    """

    def test_every_entry_names_words_rather_than_a_whole_file(self):
        for rel, (allowed, reason) in gate.EXEMPT.items():
            self.assertIsNotNone(
                allowed, "%s is exempt WHOLESALE; name the words instead" % rel)
            self.assertTrue(reason, "%s has no reason" % rel)

    def test_every_exempted_word_is_a_mention_it_would_otherwise_report(self):
        for rel, (allowed, _) in gate.EXEMPT.items():
            for word in allowed:
                self.assertTrue(
                    gate.NEEDLE.search(word),
                    "%s: %r is not something this gate would report" % (rel, word))

    def test_every_exempted_word_still_occurs_where_it_is_exempted(self):
        for rel, (allowed, _) in gate.EXEMPT.items():
            path = os.path.join(_ROOT, rel)
            self.assertTrue(os.path.exists(path), "%s no longer exists" % rel)
            kind = gate.SOURCE_SUFFIXES[os.path.splitext(rel)[1]]
            with open(path, encoding="utf-8") as fh:
                code = gate.mask(fh.read(), kind)
            found = {m.group(0) for m in gate.WORD.finditer(code)}
            for word in allowed:
                self.assertIn(
                    word, found,
                    "%s no longer names %r at a code position; delete the "
                    "exemption rather than leaving a hole" % (rel, word))


class ProseIsKept(unittest.TestCase):
    """The dated change-records this branch deliberately preserved.

    Measured 2026-09-06 over the twelve extensions this gate reads, over the
    tree as the gate found it: 1857 occurrences of the word across 257 files,
    923 of them the `package` family. Every remaining one is a comment, a
    string literal or a JSON value — except the 80 code positions EXEMPT
    names (87 until the migration route was deleted later the same day).
    """

    def test_a_go_line_comment_recording_the_removal_is_not_a_hit(self):
        root = tree(**{"internal/mapdef/format.go": '''package mapdef

// Map has no Pack field any more: 2026-09-02-art-is-a-flat-library Task 7
// deleted mapdef.Pack, and art resolves by filename through internal/artlib.
type Map struct{}
'''})
        try:
            code, out, err = run(root)
            self.assertEqual(code, 0, err)
            self.assertIn("clean", out)
        finally:
            shutil.rmtree(root)

    def test_a_go_block_comment_recording_the_removal_is_not_a_hit(self):
        root = tree(**{"internal/gateway/metadata.go": '''package gateway

/*
 * GET /api/packs/{pack}/{file} became GET /api/art/{file}: the route serves
 * one flat directory, so it takes one segment.
 */
func Serve() {}
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_go_string_literal_asserting_the_absence_is_not_a_hit(self):
        root = tree(**{"internal/mapdef/load_test.go": '''package mapdef

func TestX(t *testing.T) {
	if !strings.Contains(err.Error(), `field "pack"`) {
		t.Fatal("no")
	}
	got := "/api/packs/mossy-keep/planks_03.png"
	_ = got
}
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_typescript_comment_and_string_are_not_hits(self):
        root = tree(**{"client/src/session.ts": '''// packFileURL used to build /api/packs/{pack}/{file}
const label = "pack";
const other = 'packs';
const tpl = `a pack b`;
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_python_comment_and_docstring_are_not_hits(self):
        root = tree(**{"tools/check-thing.py":
                       '"""A docstring naming the pack, as this gate\'s own does."""\n'
                       "\n"
                       "# packs left 2026-09-02, not corrected\n"
                       "X = 1\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_proto_comment_is_not_a_hit(self):
        root = tree(**{"contract/vtt/v1/maps.proto": '''syntax = "proto3";
// This message never carried a pack: art crosses the wire by filename.
message MapRef { string id = 1; }
'''})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)


class JSONKeysAreCodePositions(unittest.TestCase):
    """In JSON the object KEY is the field name; the value is data."""

    def test_a_map_file_declaring_the_field_is_caught(self):
        root = tree(**{"campaigns/example/maps/cellar.json": (
            '{\n'
            '  "id": "cellar",\n'
            '  "pack": "cellar-basics",\n'
            '  "tiles": {}\n'
            '}\n')})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("cellar.json:3", err)
            self.assertIn("pack", err)
        finally:
            shutil.rmtree(root)

    def test_a_scenario_step_naming_the_container_is_caught(self):
        root = tree(**{"scenarios/smoke.json": (
            '{\n'
            '  "steps": [\n'
            '    {"by": "dm", "command": {"load_map": {"pack_id": "keep"}}}\n'
            '  ]\n'
            '}\n')})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("pack_id", err)
        finally:
            shutil.rmtree(root)

    def test_json_values_are_data_and_not_hits(self):
        root = tree(**{
            "scenarios/story.json": (
                '{\n'
                '  "name": "the pack, and why it left",\n'
                '  "steps": [\n'
                '    {"command": {"addNarration": '
                '{"text": "The DM installs a pack of tiles."}}}\n'
                '  ]\n'
                '}\n'),
            "internal/a/a.go": "package a\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_json_file_that_does_not_parse_is_still_scanned(self):
        """The masker is a tokenizer, deliberately, not json.loads: a
        half-written fixture would otherwise go unchecked, silently."""
        root = tree(**{"campaigns/example/maps/broken.json": '{"pack": "keep"'})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("pack", err)
        finally:
            shutil.rmtree(root)


class ScopeAndExemptions(unittest.TestCase):
    def test_generated_output_is_out_of_scope(self):
        """contract/gen is regenerated, not written; check:drift owns it."""
        root = tree(**{"contract/gen/go/x.pb.go":
                       "package genpb\n\nfunc loadPack() {}\n",
                       "internal/a/a.go": "package a\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_a_gen_directory_that_is_not_the_generated_one_is_still_scanned(self):
        """The skip is anchored to PATHS, not to the name `gen`."""
        root = tree(**{"internal/foo/gen/hidden.go":
                       "package gen\n\nfunc packSecret() {}\n",
                       "contract/gen/go/x.pb.go":
                       "package genpb\n\nfunc packThing() {}\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packSecret", err)
            self.assertNotIn("packThing", err)
        finally:
            shutil.rmtree(root)

    def test_every_javascript_and_typescript_spelling_is_scanned(self):
        for name in ["client/src/a.js", "client/src/b.jsx", "client/src/c.tsx",
                     "client/src/d.mjs", "client/src/e.cjs", "client/src/f.mts",
                     "client/src/g.cts"]:
            root = tree(**{name.replace("/", "__"):
                           "export function loadPackImages() {}\n"})
            try:
                code, _, err = run(root)
                self.assertEqual(code, 1, name)
                self.assertIn("loadPackImages", err)
            finally:
                shutil.rmtree(root)

    def test_a_file_that_cannot_be_read_fails_rather_than_being_skipped(self):
        """A source file this gate cannot read is one it cannot clear."""
        root = tree(**{"internal/a/a.go": "package a\n"})
        try:
            pathlib.Path(root, "internal/a/b.go").write_bytes(b"package a\n// \xff\xfe\n")
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("could not read", err)
            self.assertIn("b.go", err)
        finally:
            shutil.rmtree(root)

    def test_vendored_and_build_output_is_out_of_scope(self):
        root = tree(**{"client/node_modules/p/i.ts": "export function loadPack() {}\n",
                       "cmd/vtt/webdist/a.ts": "export function loadPack() {}\n",
                       "internal/a/a.go": "package a\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 0, err)
        finally:
            shutil.rmtree(root)

    def test_an_exemption_allows_only_the_words_it_names(self):
        """Per WORD, not per file — the property that keeps this gate honest.

        The standard baseline's own module is allowed to say
        `standardPackFileURL`, and is still scanned for every OTHER spelling,
        so the file with the most legitimate mentions does not become the one
        blind spot.
        """
        allowed = ("export function standardPackFileURL(b: string, f: string) {\n"
                   "  return `${b}/std-pack/${f}`;\n"
                   "}\n")
        root = tree(**{"client/src/view/pack-assets.ts": allowed})
        exempt = {"client/src/view/pack-assets.ts":
                  ({"standardPackFileURL"}, "the standard baseline's own URL builder")}
        try:
            hits, scanned, unreadable = gate.findings(root, exempt)
            self.assertEqual(hits, [])
            self.assertEqual(scanned, 1)
            self.assertEqual(unreadable, [])
        finally:
            shutil.rmtree(root)

        root = tree(**{"client/src/view/pack-assets.ts":
                       allowed + "export function loadPackImages() {}\n"})
        try:
            hits, _, _ = gate.findings(root, exempt)
            self.assertEqual([w for _, _, w in hits], ["loadPackImages"])
        finally:
            shutil.rmtree(root)

    def test_a_tree_with_nothing_to_scan_fails_rather_than_passing(self):
        """Scanning 0 files while exiting 0 is a gate that enforces nothing."""
        root = tree(**{"README.md": "no code here\n"})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("scanned no files", err)
        finally:
            shutil.rmtree(root)

    def test_a_clean_tree_reports_what_it_scanned(self):
        root = tree(**{"internal/a/a.go": "package a\n",
                       "client/src/b.ts": "export const b = 1;\n"})
        try:
            code, out, err = run(root)
            self.assertEqual(code, 0, err)
            self.assertIn("2 files", out)
        finally:
            shutil.rmtree(root)


class TheMaskerResumesAfterAClosedConstruct(unittest.TestCase):
    """Every masked construct must END, and nothing else asserts that.

    Every "must not fire" case above puts the word INSIDE a comment, a string, a
    raw string, a docstring or a template literal with nothing after it. An
    over-blanking regression — any one branch running to end-of-file instead of
    to its closing delimiter — leaves all of them green while blinding the gate
    across the rest of the file, silently. Each case here puts a real code
    position AFTER a closed construct and demands it still be found.
    """

    def test_code_after_a_closed_go_raw_string_is_still_scanned(self):
        body = ("package store\n"
                "\n"
                "var s = `a pack inside a raw string`\n"
                "\n"
                "func packAfterARawString() {}\n")
        root = tree(**{"internal/store/a.go": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAfterARawString", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_block_comment_is_still_scanned(self):
        body = ("package engine\n"
                "\n"
                "/* a pack used to be loaded here. */\n"
                "\n"
                "func packAfterABlockComment() {}\n")
        root = tree(**{"internal/engine/apply.go": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAfterABlockComment", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_line_comment_is_still_scanned(self):
        body = ("package engine\n"
                "\n"
                "// a pack used to be loaded here.\n"
                "func packAfterALineComment() {}\n")
        root = tree(**{"internal/engine/b.go": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAfterALineComment", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_python_docstring_is_still_scanned(self):
        body = ('"""A docstring mentioning the pack."""\n'
                "\n"
                "def pack_after_a_docstring():\n"
                "    return 1\n")
        root = tree(**{"tools/thing.py": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("pack_after_a_docstring", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_template_literal_is_still_scanned(self):
        body = ("const t = `a pack inside a template`;\n"
                "export function packAfterATemplate() {}\n")
        root = tree(**{"client/src/view/dm.ts": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAfterATemplate", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_regex_literal_is_still_scanned(self):
        """The regex branch GUESSES, so a wrong guess must stay bounded."""
        body = ("const r = /pack/i;\n"
                "export function packAfterARegex() {}\n")
        root = tree(**{"client/test/x.test.ts": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("packAfterARegex", err)
        finally:
            shutil.rmtree(root)

    def test_code_after_a_closed_json_value_is_still_scanned(self):
        body = ('{\n'
                '  "note": "a pack inside a value",\n'
                '  "pack": "keep"\n'
                '}\n')
        root = tree(**{"campaigns/example/maps/m.json": body})
        try:
            code, _, err = run(root)
            self.assertEqual(code, 1)
            self.assertIn("m.json:3", err)
        finally:
            shutil.rmtree(root)


if __name__ == "__main__":
    unittest.main(verbosity=2)
